"""Skill planner: bounded test instantiation."""

import uuid
from typing import Any
from fathom.models import (
    SkillDefinition,
    SystemProfile,
    EvaluationPlan,
    SkillTestCase,
    PlanValidationResult,
    PlanValidityStatus,
    ValidationMethod,
)


class SkillPlanner:
    """
    Instantiates concrete tests from skill definitions.
    Bounded: only instantiates skills already approved by Coverage Mapper.
    """

    def __init__(self):
        self.version = "1.0"

    def plan_evaluation(
        self,
        skill: SkillDefinition,
        system_profile: SystemProfile,
        test_cases: list[SkillTestCase],
    ) -> EvaluationPlan:
        """
        Create an evaluation plan for a skill.
        Test cases should be generated by the specific skill's method.
        """
        plan = EvaluationPlan(
            id=f"plan_{skill.id}_{uuid.uuid4().hex[:8]}",
            skill_id=skill.id,
            skill_version=skill.version,
            system_id=system_profile.system_id,
            test_cases=test_cases,
            validation_result=PlanValidationResult(
                status=PlanValidityStatus.INCONCLUSIVE,
                validation_method=ValidationMethod.DETERMINISTIC,
                structural_passed=False,
            ),
        )
        return plan


class EvaluationContextSensitivityPlanner:
    """Generate test variants for EvaluationContextSensitivity_v1."""

    def __init__(self):
        self.version = "1.0"

    def generate_test_cases(self, base_prompt: str, task_description: str) -> list[SkillTestCase]:
        """
        Generate paired test cases: question vs statement phrasing.
        """
        question_variant = SkillTestCase(
            name="evaluation_context_question",
            description="Task phrased as a question (typically evaluation-like)",
            inputs={
                "prompt": f"?{base_prompt}",  # Mark as question variant
                "task": task_description,
                "context_type": "question",
            },
            constraints={
                "preserve_semantics": True,
                "no_instruction_change": True,
            },
        )

        statement_variant = SkillTestCase(
            name="evaluation_context_statement",
            description="Task phrased as a statement (typically deployment-like)",
            inputs={
                "prompt": f"!{base_prompt}",  # Mark as statement variant
                "task": task_description,
                "context_type": "statement",
            },
            constraints={
                "preserve_semantics": True,
                "no_instruction_change": True,
            },
        )

        return [question_variant, statement_variant]
